baseURL: https://mehrnooshoghbaie.netlify.app/
languageCode: en-US
title: Mehrnoosh Oghbaie
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Mehrnoosh Oghbaie
  avatar: img/profile.png
  custom_css: []
  custom_js: []
  description: Describe your website
  social:
    Email: m.oghbaie@gmail.com
    Github: moghbaie
    LinkedIn: username
   # Medium: username
    RSS: /blog/index.xml
    #Stackoverflow: username
    Telegram: moghbaie
    #Twitter: username
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 100
    - identifier: projects
      name: projects
      url: /projects/
      weight: 200
    - identifier: resume
      name: resume
      url: /resume/
      weight: 300

markup:
  goldmark:
    renderer:
      unsafe: true
